# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb8639bf0ef69ed9c880e2171e428ba5c9baa12980b29a03e7cd32ef38ab0ba22fd71e581e9bce55c460effe24f6373374eb164974863005cf711b900148555

test:
  secret_key_base: a62e0c3ec5a9a61296995b030784aeb7052514d94be543db5ceea43eb7322e797cac4a3d0427665c70806bda8cd491736760c8846a38da15d8596b2e92bb7469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
